# Generated by Django 3.0.8 on 2020-08-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='positions_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=False),
        ),
    ]
