# Generated by Django 3.0.8 on 2020-09-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
    ]
