# Generated by Django 3.0.8 on 2020-08-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='positions_required',
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Position'),
        ),
    ]
