# Generated by Django 3.0.8 on 2020-09-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200910_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
    ]
