# Generated by Django 3.0.8 on 2020-09-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200910_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
