# Generated by Django 3.0.8 on 2020-08-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
