# Generated by Django 3.0.8 on 2020-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200831_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('DEC', 'Declined'), ('AWA', 'Awaiting')], default='AWA', max_length=3),
        ),
    ]
