# Generated by Django 3.0.8 on 2020-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200818_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('js', 'JavaScript Developer'), ('sql', 'SQL Database Specialist'), ('py', 'Python Developer')], default='js', max_length=3),
        ),
    ]
