# Generated by Django 3.0.8 on 2020-08-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_application'),
        ('accounts', '0010_profile_re_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_applications',
            field=models.ManyToManyField(to='projects.Application'),
        ),
    ]
