# Generated by Django 3.0.8 on 2020-09-02 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200901_1002'),
        ('accounts', '0011_user_re_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Declined')])),
                ('text_preview', models.CharField(blank=True, max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_appl', to='projects.Application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_from_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
