# Generated by Django 3.0.8 on 2020-09-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
